In [9]:
import numpy as np
import matplotlib.pyplot as plt

A=np.array([[1,2,3,5],[1/2,1,1/2,2],[1/3,2,1,3],[1/5,1/2,1/3,1]])
A


array([[1.        , 2.        , 3.        , 5.        ],
       [0.5       , 1.        , 0.5       , 2.        ],
       [0.33333333, 2.        , 1.        , 3.        ],
       [0.2       , 0.5       , 0.33333333, 1.        ]])

In [10]:
n=A.shape[1]
n

4

In [11]:
eig_val,eig_vec=np.linalg.eig(A)
Max_eig=max(eig_val)
Max_eig

(4.10737097093776+0j)

In [12]:
#这里的CI是一致性指标，RI是随机一致性指标,用最大的特征值和矩阵的维度来计算，如果C
CI=(Max_eig-n)/(n-1)
CI

(0.035790323645919976+0j)

In [13]:
#RI是随机一致性指标，RI的值是根据n的值来的，n是矩阵的阶数,RI的值是固定的
RI=[0,0.0001,0.58,0.90,1.12,1.24,1.32,1.41,1.45,1.49]

In [14]:
#CR是一致性比率，CR=CI/RI,RI是固定的，所以CR的值是随着CI的变化而变化的
CR=CI/RI[n-1]
CR

(0.03976702627324442+0j)

In [15]:
CI
CR

(0.03976702627324442+0j)

In [16]:
if CR<0.1:
    print('满足一致性要求')
else:
    print('不满足一致性要求')

满足一致性要求


2.算术平均数法求权重

In [18]:
import numpy as np
#定义判断矩阵
A=np.array([[1,2,4],[1/2,1,2],[1/4,1/2,1]])
#计算每一列的和,axis=0表示按列求和,axis=1表示按行求和
sum_col=np.sum(A,axis=0)
#获取A的行数和列数
n=A.shape[0]
#归一化
Stand_A=A/sum_col
#各列相加到同一行
ASumr=np.sum(Stand_A,axis=1)
#计算权重
weights=ASumr/n

weights

array([0.57142857, 0.28571429, 0.14285714])

3.几何平均法求权重

In [20]:
import numpy as np
#定义判断矩阵
A=np.array([[1,2,4],[1/2,1,2],[1/4,1/2,1]])

#计算判断矩阵的大小
n=A.shape[0]

#将判断矩阵的每一行的元素相乘得到一个新的列向量
col_vet=np.prod(A,axis=1)

#将列向量的每个元素开n次方
col_vet=col_vet**(1/n)
#将得到的列向量归一化
vet=col_vet/np.sum(col_vet)

vet

array([0.57142857, 0.28571429, 0.14285714])

3.特征值法求权重

In [21]:
import numpy as np
#定义判断矩阵
A=np.array([[1,2,4],[1/2,1,2],[1/4,1/2,1]])
#计算判断矩阵的大小
n=A.shape[0]  

#计算判断矩阵的特征值和特征向量
eig_val,eig_vec=np.linalg.eig(A)
#找到最大的特征值
Max_eig=max(eig_val)

#找到最大特征值对应的特征向量
Max_eig_vec=eig_vec[:,np.argmax(eig_val)]

#对特征向量进行归一化来计算权重
weights=Max_eig_vec/np.sum(Max_eig_vec)

weights

array([0.57142857, 0.28571429, 0.14285714])

5.计算综合评分

In [22]:
import numpy as np
#定义判断矩阵
A=np.array([[1,2,4],[1/2,1,2],[1/4,1/2,1]])
#计算判断矩阵的大小
n=A.shape[0]

#使用特征值法求解权重向量
    #计算判断矩阵的特征值和特征向量
eig_val,eig_vec=np.linalg.eig(A)
    #找到最大的特征值
Max_eig=max(eig_val)
    #找到最大特征值对应的特征向量
Max_eig_vec=eig_vec[:,np.argmax(eig_val)]
    #对特征向量进行归一化来计算权重
weights=Max_eig_vec/np.sum(Max_eig_vec)

#定义因素矩阵
B=np.array([[100,200,400],[1,2,3],[10,20,30]])
#计算因素矩阵的大小
m=B.shape[0]
#对因素矩阵的每一列进行归一化
Stand_B=B/np.sum(B,axis=0)
#将归一化的因素矩阵和权重向量相乘
result=np.dot(Stand_B,weights)
#得到的结果就是最终的评价得分
result

array([0.90417042, 0.00871178, 0.0871178 ])