In [39]:
#使用topsis进行多属性决策
import numpy as np
#请输入参评数目，即样本数目，矩阵的行数
m=3
#请输入指标数目，即矩阵的列数
n=4

In [40]:
#输入类型矩阵，该矩阵指示了每个指标的类型
print("1.极大型指标")
print("2.极小型指标")
print("3.中间型指标")
print("4.区间型指标")
kind=input("请输入指标类型：").split(" ")#split函数用于分割字符串，返回一个列表
kind

1.极大型指标
2.极小型指标
3.中间型指标
4.区间型指标


['1', '2', '3', '4']

In [41]:
#初始化一个m*n的矩阵
A=np.zeros((m,n))
#输入数据矩阵
for i in range(m):
    A[i]=input().split(" ")
    A[i]=list(map(float,A[i]))
A

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [42]:
#将极小型数据转化为极大型数据
def minToMax(maxx,x):
    x=list(x)
    ans=[]
    for i in range(len(x)):
        ans.append(maxx-x[i])
    return ans

#将中间型数据转化为极大型数据
def midToMax(bestx,x):
    x=list(x)
    ans=[]
    h=[]
    #计算列表中每个元素与最优值的差的绝对值
    for i in range (len(x)):
        h.append(abs(bestx-x[i]))
    M=max(h)#计算最大值,用来归一化
    if M==0:
        M=1#防止除0错误
    #计算每个元素的极大型值
    for i in range(len(x)):
        ans.append(1-h[i]/M)
    return np.array(ans)

#将区间型数据转化为极大型数据
def intervalToMax(x,lowx,highx):
    x=list(x)
    ans=[]
    for i in range(len(x)):
        if x[i]>=lowx and x[i]<=highx:
            ans.append(1)
        elif x[i]<lowx:
            ans.append(1-(lowx-x[i])/(lowx-min(x)))
        elif x[i]>highx:
            ans.append(1-(x[i]-highx)/max(x)-highx)
    return np.array(ans)

In [43]:
#统一指标类型
for i in range(n):
    if kind[i]=='1':
        A[:,i]=A[:,i]
    elif kind[i]=='2':
        A[:,i]=minToMax(max(A[:,i]),A[:,i])
    elif kind[i]=='3':
        print("请输入中间型指标的最优值：")
        bestx=int(input())
        A[:,i]=midToMax(bestx,A[:,i])
    elif kind[i]=='4':
        print("请输入区间型指标的最小值和最大值：")
        lowx=int(input())
        highx=int(input())
        A[:,i]=intervalToMax(A[:,i],lowx,highx)
A

请输入中间型指标的最优值：


请输入区间型指标的最小值和最大值：


array([[ 1.        ,  2.        ,  0.66666667, -2.16666667],
       [ 2.        ,  1.        ,  0.33333333, -2.33333333],
       [ 3.        ,  0.        ,  0.        , -2.5       ]])

In [44]:
#对数据矩阵进行按列归一化
for i in range(n):
    A[:,i]=A[:,i]/np.sqrt(sum(A[:,i]**2))
#打印归一化后的数据矩阵
A

array([[ 0.26726124,  0.89442719,  0.89442719, -0.53520153],
       [ 0.53452248,  0.4472136 ,  0.4472136 , -0.57637088],
       [ 0.80178373,  0.        ,  0.        , -0.61754023]])

In [47]:
#计算最小距离
x_max=np.max(A,axis=0) #求每一列的最大值
x_min=np.min(A,axis=0) #求每一列的最小值
#计算最优解和最劣解
d_z=np.sqrt(np.sum(A-np.tile(x_max,(m,1)),axis=1)**2) #计算最优解


[1.5209140936770544, 0.8525787961099317, 0.18424349854280941]